### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by garyrob** [dkirchhof/rescript-sql#1]
I was looking for a way to use sqlite3 from ReScript and came across this project. I immediately had a question. Your example.res uses an asynchronous approach, as in:

`let exec = sql =>  connection->SQLite3.exec(sql)->AsyncResult.ok`

But sqlite3 is synchronous and better-sqlite3, which you use, makes a point that it's synchronous too (in contrast to node-sqlite3). Why do you use async?

**Comment by dkirchhof** [comment]
Hey, if I want to use another db like MySQL, which isn't synchronous, the switch would be simpler. So I made all examples asynchronous, but it wouldn't be necessary.

**Comment by garyrob** [comment]
Makes sense! :)
